### ISSUE TITLE
Java demangler gives broken results for some classes in Java APIs

### ISSUE THREAD

**Issue by haeter525** [rizinorg/rz-libdemangle#23]
As described in rizinorg/rizin#2648, the Java demangler tries to remove any "java/lang/" strings from a mangled class/method/field (on line 274 of [java.c](https://github.com/rizinorg/rz-libdemangle/blob/main/src/java.c)).

It's a nice feature that simplifies the demangled result for classes in the [java.lang](https://docs.oracle.com/javase/7/docs/api/java/lang/package-summary.html) package. However, it also breaks those with package names starting with "java.lang", such as classes in [java.lang.annotation](https://docs.oracle.com/javase/7/docs/api/java/lang/annotation/package-summary.html), [java.lang.reflect](https://docs.oracle.com/javase/7/docs/api/java/lang/reflect/package-summary.html), [java.lang.invoke](https://docs.oracle.com/javase/7/docs/api/java/lang/invoke/package-summary.html), etc.

For example, in the following screenshot, the demangler takes the method, `getMethod(Ljava/lang/Class;)Ljava/lang/reflect/Method;`, as the input and returns `reflect.Method getMethod(Class)`. The result shows that the return type is `reflect.Method`. But according to the input, it should be `java.lang.reflect.Method`.

![](https://i.imgur.com/AvtvXBR.png)

### Expected behavior

The Java demangler performs more checks to avoid only removing parts of the package name.

### Actual behavior

The Java demangler removes all the "java/lang" strings from the input. Thus, it generates broken demangled results for some classes in Java APIs.

### Steps to reproduce the behavior

- Please open [this sample](https://github.com/quark-engine/apk-malware-samples/raw/master/Ahmyth.apk) with the latest Rizin.
- Run the following commands.

```
aaa
is~2768
```

Also, please feel free to let me know if I've missed something. I can work on the PR if this is indeed an issue.

**Comment by wargio** [comment]
maybe i can simplify only some classes names of well known packages..

**Comment by wargio** [comment]
i guess we can try to limit this or always show them.

**Comment by haeter525** [comment]
I hadn't considered the latter option. :D
If it's viable, I will prefer it the most since it keeps the result the same as what Rizin gets from the binaries.

**Comment by wargio** [comment]
ok, i will change this for the next release
