### ISSUE TITLE
Support GNUv2 C++ mangling scheme

### ISSUE THREAD

**Issue by XVilka** [rizinorg/rz-libdemangle#8]
Support GNUv2 C++ mangling scheme

How to reproduce:
```
[0x00000000]> iD c++ _AddColor__10ZafDisplayUcUcUcUcUc
# Get nothing
```

Currently demangling is implemented in `librz/bin/mangling/*`. The code on which the current GNU demangler is based on might have supported the V2 scheme as it contains `gnu_demangling` and `gnu_v3_demangling` in the list mangling styles.

See "8.4 Gnu 2 name mangling" chapter of the [calling_conventions.pdf](https://github.com/rizinorg/rizin/files/6154867/calling_conventions.pdf) to understand the mangling syntax.

cc @karliss

**Comment by wargio** [comment]
This adds support but is GPL.
https://github.com/rizinorg/rz-libdemangle/pull/41
